<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Welcome to Cool & Heat Company' => 'Bienvenido a Cool & Heat',
    '24/7 Emergency Available' => 'Respuesta a Emergencias',
    'Expert and Professional' => 'Experto y Profesional',
    'Satisfaction Guarantee' => 'Satisfacción garantizada',
    'Free Estimation' => 'Estimación gratuita',
    'about_text' => 'Somos  una empresa familiar dedicada a la instalación, reparación y mantenimiento de equipos de climatizacion, con más de 10 años de experiencia operando en el estado de la Florida. Desde nuestros inicios hemos logrado reunir un equipo capacitado de tecnicos e ingenieros, lo cual nos ha permitido agregar nuevos servicios como reparación y mantenimiento de instalaciones  electricas.',
    'Hello, Meet Us!'=>'Hola, Conócenos!',
    'Cool&Heat, always here for you'=>'Cool&Heat, siempre a su disposición',
    'wellcome_home_text' => 'Apoyados en los años de experiencia de nuestro equipo de trabajo podemos garantizar un servicio de calidad.<br/> La satisfacción de nuestros clientes es nuestra prioridad.',
    'Services'=>'Servicios',
    'What we offer'=>'Que ofrecemos',
    'offer_text'=>'Brindar siempre un mejor servicio con atención personalizada en Ingles y Español es nuestro objetivo .<br/> Por ello disponemos de los mejores profesionales.',
    'service_desc'=>'Sabemos que su casa es <br/>importante para usted..',
    'service_desc1'=>'Le ayudamos a mantener su <br/>sistema de energía seguro',
    'Ac_service'=>'Calefacción, Ventilación & Aire acondicionado',
    'E_service'=>'Instalaciones eléctricas y solución de problemas',
    'Contact Us'=>'Contactenos',
    'contact_text'=>'No dude en llamar en cualquier momento 1-305-834-1281 <br/> o rellenar este formulario',
    'slide1_text1'=>'Bienvenidos a <strong>Cool&Heat,</strong> climatización &amp; sistemas eléctricos',
    'slide1_text2'=>'Servicio Residencial, Comercial <br/>e Industrial',
    'slide2_text1'=>'<strong>24/7</strong> Instalaciones eléctricas y solución de problemas',
    'slide2_text2'=>'Inspecciones, reemplazo, <br class="hidden-xs"> mantenimiento',
    'read more'=>'leer más',
    'About'=>'Nosotros',
    'Services'=>'Servicios',
    'Ac Services'=>'Servicios Ac',
    'Electric Services'=>'Servicios Eléctricos',
    'All'=>'Todos',
    'Commercial'=>'Comercial',
    'Recidential'=>'Recidencial',
    'Emergency'=>'Emergéncia',
    'Electrical Services'=>'Servicios Eléctricos',
    'Submit'=>'Enviar',
    'Name'=>'Nombre',
    'Email'=>'Correo',
    'Phone'=>'Teléfono',
    'Address'=>'Dirección',
    'Message'=>'Mensaje',
    'Payments we accept'=>'Pagos que aceptamos',
    'Ac Repair'=>'Reparación Ac',
    'Ac Maintenance'=>'Mantenimiento Ac',
    'Ac Replacement'=>'Reempalzo Ac',
    'Ac Inspections'=>'Inspecciones Ac',
    'Ac Preventative'=>'Preventivo Ac',
    'Heatproofing'=>'Termoaislación',
    'Ventilation'=>'Ventilación',
    'Shingle Replacement'=>'Sustitución de tejas',
    'Ac Leak Repair'=>'Reparación de fugas',
    'Panel Upgrades'=>'Actualizaciones de panel',
    'Home Automation'=>'Automatización del hogar',
    'Lighting Installation'=>'Instalación de iluminación',
    'Ceiling Fan Installation'=>'Instalación de ventilador de techo',
    'Electrical Wiring Installation'=>'Instalación Cableado eléctrico',
    'Emergency Electrical Repair'=>'Reparación eléctrica de emergencia',
    'Sub Panel Installation'=>'Instalación de sub panel',
    'Surge Protection'=>'Protección contra sobretensiones',
    'Tankless Water Heater'=>'Calentador de agua sin tanque',
    'Language:'=>'Lenguaje',
    'Mon-Fri:'=>'Lun-Vie:',
    'Sat:'=>'Sab:',

];
