<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Welcome to Cool & Heat Company' => 'Welcome to Cool & Heat Company',
    '24/7 Emergency Available' => '24/7 Emergency Available',
    'Expert and Professional' => 'Expert and Professional',
    'Satisfaction Guarantee' => 'Satisfaction Guarantee',
    'Free Estimation' => 'Free Estimation',
    'about_text' => 'We are a family company with more than 10 years of experience, dedicated to the installations, repairs and maintenances of air conditioning equipments, offering our services in the State of Florida. Since our inception we have  gathered a qualified working team of technicians and engineers which have allowed us to add new services such as, repairs and maintenance of electrical installations.',
    'wellcome_home_text' => 'Backed by years of experience of our team we can guarantee quality service.<br/> The satisfaction of our customers is our priority.',
    'offer_text'=>'Always provide better service with personalized attention in English and Spanish is our goal.<br/> Therefore we have the best professionals.',
    'service_desc'=>'We know your home is<br/> important to you..',
    'service_desc1'=>'We help you keep you <br/> system secure energy',
    'Ac_service'=>'Heating, ventilation, air conditioning',
    'E_service'=>'Electrical installations and troubleshooting ',
    'contact_text'=>'Feel free to call us anytime (888) 888-8888 <br/> or fill out this form',
    'slide1_text1'=>'Welcome to <strong>Cool&Heat,</strong> Heating &amp; Cooling Services',
    'slide1_text2'=>'Residential, Commercial and Industrial<br>Cool&Heat Contractor',
    'slide2_text1'=>'<strong>24/7</strong> Electrical installations and troubleshooting',
    'slide2_text2'=>'Inspections, Replacement , <br class="hidden-xs"> Maintenance ',
];
